### PR TITLE
Small grammar changes

### PR DESCRIPTION
**Pull request by Tanner016**
What has been changed?  
 
I made some changes to the ReadMe section which simply updated the grammatical structure. This sounds like a fun project, and as someone who has studied extensively in English grammar, I am more then willing to go through the entire ReadMe section and update if desired! Thanks

### CODE REVIEW

**Comment by tylim88** [comment]
appreciate for the work, we really need someone who is good in English

I will merge this request and make some change in the readme, then you can continue

If you need faster response please find us in ztm discord gamesenshi channel

**Comment by Tanner016** [comment]
Sounds good! I'll update the rest of the readme for your review, and am
hoping to help out where I can on the other parts of the project. Thanks

**Comment by tylim88** [comment]
Thank for the help

Btw I just finish adding new content in readme, please sync your fork first before you continue

you are also welcome to add new content to make the readme project oriented

**Comment by Tanner016** [comment]
Will do

**Comment by CodeMeKathy** [comment]
Hi Tanner,

Thank you for your contributions and welcome to the team. Would you mind sharing your discord username? I tried to find you, but was unsuccessful. Have you had a chance to official join the discord project channel?
Thank you in advance.
Kathy Lambert
Software Developer | Project Manager

E: Kathy@KathyLambert.me (mailto:Kathy@KathyLambert.me)
P: 504.407.1754 (tel:504.407.1754)
W: https://kathylambert.me

**Comment by Tanner016** [comment]
Hey, I have a discord but I use it for gaming/streaming. I was maybe going
to create a separate one. For now though, my name is Stoker016.

**Comment by CodeMeKathy** [comment]
Hey,

Gotcha. So have you actually joined the ZtM Discord group? We use discord as a method of communication for the group and project.
If not see the link below and I believe you can setup/use any username of your choice.
Let me know if you have any questions or if I can be of assistance.
https://discord.gg/dKknDrv
Best,
Kathy Lambert
Software Developer | Project Manager

E: Kathy@KathyLambert.me (mailto:Kathy@KathyLambert.me)
P: 504.407.1754 (tel:504.407.1754)
W: https://kathylambert.me

**Pull request merged**
